POST http://localhost:3003/api/blogs/66abc1db8cc24d2885014495/comments
Content-Type: application/json

{ 
    "content": "Install the library with the command",
    "blogId": "66abc1db8cc24d2885014495"
}

###

GET http://localhost:3003/api/comments/

###

POST http://localhost:3003/api/comments
Content-Type: application/json

{ 
    "content": "подробностей записи в блоге",
    "blogId": "66c445a061e781370d475acb"

}

###

DELETE http://localhost:3003/api/comments/xxxx...xxxxxxxxx
